### ISSUE TITLE
Document logging best practices

### ISSUE THREAD

**Issue by thebho** [maryvilledev/skilldirectory#111]
How to handle/rethrow errors.  Which log type to use in each instance. How to change logging level.

**Comment by Hopding** [comment]
I've added some pages to the wiki that should address this:

* https://github.com/maryvilledev/skilldirectory/wiki/Logging
* https://github.com/maryvilledev/skilldirectory/wiki/Make-File
* https://github.com/maryvilledev/skilldirectory/wiki/Error-Handling

Any feedback you might have would be awesome to hear 👍
