### ISSUE TITLE
Discuss refactoring callbacks

### ISSUE THREAD

**Issue by dane-johnson** [maryvilledev/skilldirectory#138]
replace naked callbacks with callbacks wrapped in arrow functions

**Comment by thebho** [comment]
Can you give an example and link to some documentation?

**Comment by dane-johnson** [comment]
`<Button onClick={this.confirm} name="Yes">Yes</Button>` 
would become
`<Button onClick={() => this.confirm()} name="Yes">Yes</Button>`

**Comment by dane-johnson** [comment]
http://stackoverflow.com/questions/33631482/react-this-is-null-in-event-handler#33631520

**Comment by Hopding** [comment]
I prefer to bind methods in the class constructor. I think it is significantly more clear what is actually being done that way. I do not think there is any functional difference, though. See section [_**ECMAScript 2015 classes**_](http://reactkungfu.com/2015/07/why-and-how-to-bind-methods-in-your-react-component-classes/) for the following example:

```javascript
class InputExample extends React.Component {
  constructor(props) {
    super(props);

    this.state = { text: '' };
    this.change = this.change.bind(this);
  }

  change(ev) {
    this.setState({ text: ev.target.value });
  }

  render() {
    let { text } = this.state;
    return (<input type="text" value={text} onChange={this.change} />);
  }
}
```

**Comment by solkaz** [comment]
What [Facebook recommends](https://facebook.github.io/react/docs/handling-events.html) is that you bind a method in the class constructor or use property initializer syntax:

```
class Foo extends React.Component {
  // constructor and stuff
  // ...
  boundMethod = (args) => {
    // Access to class' instance of this in this method
  }
}
```

The latter is in stage 2 however, so it's not stable. The safest thing would be to bind in the class constructor for the time being.

**Comment by Hopding** [comment]
@thebho @dane-johnson @jdmaryville @solkaz So have we decided that constructor binding is preferred? Also, this issue was meant for the _skilldirectoryui_ project.

**Comment by dane-johnson** [comment]
Think we can call this one closed?

**Comment by Hopding** [comment]
Seems reasonable to me
