### ISSUE TITLE
When performing a GET all skillReviews, only return the 10 most recent

### ISSUE THREAD

**Issue by thebho** [maryvilledev/skilldirectory#147]
Cassandra Documentation: http://docs.datastax.com/en/tutorials/Time_Series.pdf

Here is a good example of how to handle this in REST: https://github.com/WhiteHouse/api-standards#record-limits

So the default would be:
```
limit: 10
offset: 0
```
With the ability to override

**Comment by dane-johnson** [comment]
This may need to wait until [#151](https://github.com/maryvilledev/skilldirectory/issues/151) is done.
