### ISSUE TITLE
Replace http-server with Go code

### ISSUE THREAD

**Issue by Hopding** [maryvilledev/skilldirectory#171]
Right now, we are using npm's `http-server` command line utility to host locally stored skill icons via port `2121`, so that the frontend can access them. I propose removing this external dependency, and using Go code to run the static file server. It turns out, [this can be done in about one line of code](https://github.com/golang/go/wiki/HttpStaticFiles) (because Go is just that awesome):

```go
http.ListenAndServe(":2121", http.FileServer(http.Dir("/usr/share/doc")))
```

**Comment by thebho** [comment]
Were you thinking a goroutine if you are running locally, or a separate executable that can be run from the make file?

**Comment by Hopding** [comment]
I think a goroutine would be better. That way it is all contained within the program, and makes life simpler for the developer.
