### ISSUE TITLE
Invstigate Possible regressions

### ISSUE THREAD

**Issue by dane-johnson** [maryvilledev/skilldirectory#173]
These two commits (https://github.com/maryvilledev/skilldirectory/commit/c98fb422c17d6516e59fcd17f4e074038e483d61, https://github.com/maryvilledev/skilldirectory/commit/7c189e619545fd4459b65c11bfdb9e04b9623950) seem to have caused some regression in the skilldirectory. Investigate the extent of the damage, and look into possible solutions.

**Comment by dane-johnson** [comment]
Both commits are part of this PR. https://github.com/maryvilledev/skilldirectory/pull/161

**Comment by solkaz** [comment]
What specific examples of regressions are you noticing?

**Comment by dane-johnson** [comment]
The red flag was that the `SanitizeInput` function introduced here (https://github.com/maryvilledev/skilldirectory/pull/159) is no longer in the cassandra.go file.

**Comment by dane-johnson** [comment]
Other than that, the full extent is unknown.

**Comment by Hopding** [comment]
~`SanitizeInput` is in the `util.go` file. It seems to still exist in the current master branch: https://github.com/maryvilledev/skilldirectory/blob/master/util/util.go#L91~ Nevermind. You meant it wasn't being called on `Save` anymore, which is true.

**Comment by dane-johnson** [comment]
Yeah I think I actually re-introduced it on a later commit, but I think it was removed as well.

**Comment by thebho** [comment]
This is a little vague.  Let's just keep improving our testing
