### ISSUE TITLE
Add a TMSkill type that maps a team member to a skill

### ISSUE THREAD

**Issue by thebho** [maryvilledev/skilldirectory#18]
TMSkill {
ID string,
SkillID string,
TeamMemberID string,
WishList bool,  //Let talks about this more
SkillSet bool,
Proficiency int,  (limited to 0-5)
}

**Comment by Hopding** [comment]
I know we discussed this a bit, a week or so ago. So, I want to confirm what it is that we decided on before I implement anything:

We want a `TMSkill` type - and a new table for it - that will allow us to link `TeamMember`s to the `Skill`s that they possess. Each instance of the `TMSkill` type will contain a single `Skill`, a flag to determine if it is on their 'WishList' or not, and their proficiency in that `Skill` (presumably, `Skill`s on a 'WishList' will have a proficiency of 0)? The `TMSkill` type will look as you outlined above:
```
TMSkill {
  ID string,
  SkillID string,
  TeamMemberID string,
  WishList bool, //Let talks about this more
  SkillSet bool,
  Proficiency int // (limited to 0-5)
}
```

**Comment by thebho** [comment]
Yeah, this is still valid.  I wouldn't assume that `WishList == Proficiency 0`. I may have some basic knowledge of a skill but still want to learn more.

Less say that you can add a new TMSkill, it has to have a valid `SkillID` and TeamMemberID, the `WishList` and `SkillSet` are optional, and the Proficiency has to be between 0-5.
