### ISSUE TITLE
Add postgres connector as a DataAccessor type

### ISSUE THREAD

**Issue by thebho** [maryvilledev/skilldirectory#195]
Connect to docker backend with creds
- [ ] Recover Filter logic for skill_type and link_type

**Comment by dane-johnson** [comment]
Any literature on this? Not sure what it means.

**Comment by thebho** [comment]
Pretty much implement the `DataAccess` Interface with a Postgres implementation.  Use the new implementation to switch out the CassandraConnector inside the router and implement new Read,Save,Delete etc.. functions

**Comment by dane-johnson** [comment]
Would like to close this, as it was decided to abandon this interface.
Progress on new database integration should be on https://github.com/maryvilledev/skilldirectory/issues/196.
