### ISSUE TITLE
Add an endpoint for editing a TMSkill from a TeamMember list

### ISSUE THREAD

**Issue by thebho** [maryvilledev/skilldirectory#20]
Calling a put a tmskills/id should update or remove a tmskill

**Comment by Hopding** [comment]
Shouldn't `TMSkill` removal occur in response to a DELETE request? I thought PUT requests were generally reserved for updates only?

**Comment by thebho** [comment]
Correct.

**Comment by thebho** [comment]
To Clarify:
POST: Validate Fields, Create ID,  Save
PUT: Validate ID, Validate Fields, Save
Share as much functionality as possible
