### ISSUE TITLE
When posting to /skills/ the name and skill type fields are required

### ISSUE THREAD

**Issue by thebho** [maryvilledev/skilldirectory#33]
Posting {"ame":"Java","SkillType":"scripted"}
Adds a new Skill with a nil name, it should throw an error and return a bad status code

**Comment by Hopding** [comment]
Just to confirm I understand what you are looking for:
When posting a new skill, if the request's JSON does not contain valid fields for the `name` and `SkillType`, an error should be generated and the server should respond with a bad status code? 

What if the JSON contains extraneous information, e.g. `{"name":"Java","SkillType":"scripted","candy":"lollipops"}`? Should the server quietly ignore it, or somehow indicate to the client that the "candy" field is not valid?

Also, should the fields and/or values be case sensitive, or insensitive?

**Comment by thebho** [comment]
`Name` and `SkillType` should be required to add a new Skill.  We are not concerned with unrecognized fields/keys on a POST, and I don't think we will ever be.
