### ISSUE TITLE
The skills controller should return a 400 (Bad Request) response when calling DELETE without an id

### ISSUE THREAD

**Issue by thebho** [maryvilledev/skilldirectory#37]
404 Is correct when the id doesn't exist

Also add another the TestRemoveSkillError test.  One test for each type of error.

**Comment by Hopding** [comment]
Right now, the `skills.removeSkill()` function is capable of generating two different errors - one for each scenario you mentioned. However, the way for the caller of the function to determine which of the two errors was generated is by inspecting the error's string itself.

It seems that a more robust approach would be to create a new package called `errors` and use it to hold various different error types. In this case, the package would contain two errors:
`type BadRequest400Error error` and `type NoSuchID404Error error`

**Comment by thebho** [comment]
I agree with creating custom errors, I'm not sure about tying the StatusCode to the error is the right move.  StatusCodes are specifically for consumers to handle, Error names are for developers to parse and troubleshoot.  Issue #34 is in the Backlog to flesh out the creating/handling in the SkillsController.  Let's move this discussion there, and not let it hold up the completion of this story.

**Comment by Hopding** [comment]
I didn't mean to suggest adding a `statusCode` field to the custom errors. I meant create custom errors to differentiate between the two types of errors that `removeSkill()` can return. So, in the `SkillHandler()` function, we would have:
```go
case http.MethodDelete:
	err = removeSkill(r)

	switch err.(type) {
	case *errors.NoSuchID404Error:
		statusCode = http.StatusNotFound
	case *errors.BadRequest400Error:
		statusCode = http.StatusBadRequest
	}
}
```
Otherwise, the only way to figure out if the error generated by `removeSkill()` is due to a nonexistent ID, or a missing ID, is to parse the returned error's string, which is not very robust.

**Comment by thebho** [comment]
I do see the benefit in doing it that way.  It's probably a more elegant way to match error codes to status codes.

I'm still concerned with using the status code in the error type.  Let the skills controller say what the error is, and let the BaseController decide how to map the error types to status codes.  I don't think it's always going to be 1-to-1, Error-to-Status.  So a GET on a non existent Skill would return a `NoSuchIDError` and the BaseController would hand the mapping of the that type to a status code.
