### ISSUE TITLE
Research and add license to project

### ISSUE THREAD

**Issue by thebho** [maryvilledev/skilldirectory#87]

**Comment by Hopding** [comment]
I've gone through the dependencies in the `vendor/` directory to see what
licenses they have. There are a couple that I was unable to find licenses
for, but the rest used either the [MIT](http://choosealicense.com/licenses/mit/) license or the [BSD-3-Clause](http://choosealicense.com/licenses/bsd-3-clause/) license:

| MIT         | BSD-3-Clause | Unsure           |
|-------------|:------------:|:----------------:|
| Logrus      | GoCQL        | golang.org/x/sys |
| go-hostpool | Snappy       | golang.org/x/net |
|             | go-inf       |                  |

So, basically, my understanding is that we should be able to use whatever
license we want to use, as long as we include the licenses  of the above 
projects with the sources of the projects we are using (and we are, it's 
all in the `vendor/` directory).

I suggest that we use the MIT license. The BSD-3-Clause also seems okay.
It is like the MIT license except that it includes:
> a 3rd clause that prohibits others from using the name of the project or its contributors to promote derived products without written consent.

I don't really think that the extra clause in the BSD-3-Clause really matter much.

@thebho do you have any thoughts on this?

**Comment by thebho** [comment]
MIT !
