### ISSUE TITLE
Design a Postman collection to run a series of requests, with tests, involving Skills and skill children.

### ISSUE THREAD

**Issue by thebho** [maryvilledev/skilldirectory#90]
Options:
https://www.soapui.org
http://blog.getpostman.com/2014/03/07/writing-automated-tests-for-apis-using-postman/

**Comment by Hopding** [comment]
Postman itself can also run tests: https://www.getpostman.com/docs/writing_tests. Might be better to go that route since we're already using Postman for manual tests.

**Comment by thebho** [comment]
How is this coming?  Is there a way to run a series of requests/tests where we Add A Skill, Add a TeamMember, Add A Review for that skill/teammember, GET that skill and confirm it only returns 1 Review?

And then clean up after it's self?

**Comment by thebho** [comment]
Changing this story name to reflect the current tasks
