### ISSUE TITLE
Skills need the ability to save, update, and delete positive/negative reviews about the language

### ISSUE THREAD

**Issue by thebho** [maryvilledev/skilldirectory#94]
I.E.

Java (compiled)
Website....  Blog...

Review
+ Jay: handles concurrency and garbage collection well
- Brian: has too much boiler plate code
+ Lane: Jars are my Jam!

A review has:
skill_id
positive bool
team_member_id
body string
date (added and/or edited)

**Comment by Hopding** [comment]
How do we want skill review updates be implemented? We haven't yet implemented updates for any of the other data, so no precedent has yet been set.

I imagine we will do it via PUT requests by specifying the existing skill review's ID at the end of the URL? E.g. `http://localhost:8080/skillreviews/[ID]`.

What data should be updateable? Just the body?

**Comment by thebho** [comment]
Right, you would do a PUT on `/skillreviews/[ID]` with a review object.  For now lets just update the review `body` and change the `date` timestamp.

**Comment by Hopding** [comment]
Should the `date` field include just the date, or the time as well? Cassandra has a `date` type: 
> [`date`] Value is a date with no corresponding time value; Cassandra encodes date as a 32-bit integer representing days since epoch (January 1, 1970). Dates can be represented in queries and inserts as a string, such as 2015-05-03 (yyyy-mm-dd)

However, this won't work if we also want the time.

**Comment by jaymeyer** [comment]
http://docs.datastax.com/en/archived/cql/3.0/cql/cql_reference/timestamp_type_r.html

**Comment by Hopding** [comment]
Perfect. Thanks Jay!

**Comment by jaymeyer** [comment]
this is identical to the 64-bit Java/Javascript storage for time data types.  Next questions are : How will you want to render dates/times/time zones for events that have a date-time?  E.g.: "2 hours ago" vs. "Dec-27-2016 2:06pm CST"  Actually github comments have a nice time-render format on this page - prolly stored as longs and rendered by JavaScript Date(long-date) conversion niftiness in the browser.

**Comment by Hopding** [comment]
I like the idea of doing the time-render github style. That seems to be the most useful/friendly to a user. @thebho is working on a REACT frontend, perhaps he has an opinion?

**Comment by jaymeyer** [comment]
I would run with storing the Timestamp type in Cassandra, then decide the date format later.  Can't go wrong with Timestamp.

**Comment by Hopding** [comment]
Sounds good 👍.
